name: Update

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "50 22 * * *" # 6:50 AM UTC+8

jobs:
  Generate:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Generate rule-set index
        run: |
          git clone -b meta --depth=1 https://github.com/MetaCubeX/meta-rules-dat.git meta
          git clone -b sing --depth=1 https://github.com/MetaCubeX/meta-rules-dat.git sing
          node generate.mjs
          openssl dgst -sha256 meta.json | sed 's/([^)]*)//g' > meta-version.txt
          openssl dgst -sha256 sing.json | sed 's/([^)]*)//g' > sing-version.txt

      - name: Create Release and Upload Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./{meta.json,sing.json,meta-version.txt,sing-version.txt}
          file_glob: true
          tag: latest
          release_name: latest
          overwrite: true
          draft: false
          prerelease: false
          body: ""
